#Requires -Version 5.1
<#
.SYNOPSIS
    Adds "Send to DMS approval" to the Windows Explorer right-click menu. It opens the DMS
    Power App with the selected file's path, so the user registers and submits it in one form.

.DESCRIPTION
    Per user (HKCU, no admin rights needed). Deploy to many PCs with a GPO logon script or Intune.
    - Installs a small handler to %LOCALAPPDATA%\DMS\Send-ToDms.ps1
    - Registers the menu item for all files (Windows 11: under "Show more options")
    - Also adds a "Send to" shortcut, which shows in the short Windows 11 menu as well
    The handler checks the file is under -RepositoryRoot, then opens:
        <AppUrl>&path=<UNC path>&name=<file name>
    The Power App reads Param("path") and Param("name") and opens the new-document form prefilled
    (docs/03 §2.5).

.PARAMETER AppUrl
    The app's web link: Power Apps > Apps > the app > ... > Details > Web link
    (https://apps.powerapps.com/play/e/<env>/a/<app>?tenantId=<tenant>).

.PARAMETER RepositoryRoot
    Only files under this root can be sent, e.g. \\FILE-SERVER\Corporate_Data. Mapped drives are
    translated to UNC paths automatically.

.EXAMPLE
    .\Install-DmsExplorerMenu.ps1 -AppUrl 'https://apps.powerapps.com/play/e/xxx/a/yyy?tenantId=zzz' -RepositoryRoot '\\FILE-SERVER\Corporate_Data_TEST'

.EXAMPLE
    .\Install-DmsExplorerMenu.ps1 -Uninstall
#>
[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingWriteHost', '',
    Justification = 'Interactive installer: coloured output is intended.')]
[CmdletBinding(SupportsShouldProcess, DefaultParameterSetName = 'Install')]
param(
    [Parameter(Mandatory, ParameterSetName = 'Install')] [ValidatePattern('^https://apps\.powerapps\.com/')] [string] $AppUrl,
    [Parameter(Mandatory, ParameterSetName = 'Install')] [string] $RepositoryRoot,
    [Parameter(ParameterSetName = 'Install')] [string] $MenuText = 'שלח לתהליך אישור DMS',
    [Parameter(Mandatory, ParameterSetName = 'Uninstall')] [switch] $Uninstall
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$dir     = Join-Path $env:LOCALAPPDATA 'DMS'
$handler = Join-Path $dir 'Send-ToDms.ps1'
$keyPath = 'HKCU:\Software\Classes\*\shell\SendToDms'
$sendTo  = Join-Path ([Environment]::GetFolderPath('SendTo')) 'DMS - Approval.lnk'

if ($Uninstall) {
    if ($PSCmdlet.ShouldProcess('DMS Explorer menu', 'Remove')) {
        Remove-Item -Path $keyPath -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -LiteralPath $sendTo, $handler -Force -ErrorAction SilentlyContinue
        Write-Host 'DMS menu removed.' -ForegroundColor Green
    }
    return
}

$sep = if ($AppUrl.Contains('?')) { '&' } else { '?' }
$handlerCode = @"
# Generated by Install-DmsExplorerMenu.ps1 - opens the DMS Power App for one file.
param([Parameter(Mandatory)] [string] `$File)
Add-Type -AssemblyName System.Windows.Forms
`$root = '$($RepositoryRoot.TrimEnd('\').Replace("'", "''"))'
`$path = (Resolve-Path -LiteralPath `$File).ProviderPath
# Mapped drive -> UNC
if (`$path -match '^[A-Za-z]:\\') {
    `$drive = Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='`$(`$path.Substring(0,2))'" -ErrorAction SilentlyContinue
    if (`$drive -and `$drive.ProviderName) { `$path = `$drive.ProviderName + `$path.Substring(2) }
}
if (-not `$path.StartsWith(`$root + '\', [StringComparison]::OrdinalIgnoreCase)) {
    [System.Windows.Forms.MessageBox]::Show("הקובץ אינו נמצא במאגר המבוקר:``n`$root``n``nThe file is not in the controlled repository.", 'DMS', 'OK', 'Warning') | Out-Null
    return
}
`$url = '$($AppUrl.Replace("'", "''"))$sep' + 'path=' + [uri]::EscapeDataString(`$path) + '&name=' + [uri]::EscapeDataString([IO.Path]::GetFileName(`$path))
Start-Process `$url
"@

if ($PSCmdlet.ShouldProcess($handler, 'Install handler')) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
    # UTF-8 with BOM so Windows PowerShell 5.1 reads the Hebrew message correctly
    [IO.File]::WriteAllText($handler, $handlerCode, (New-Object Text.UTF8Encoding($true)))
}

$command = "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$handler`" `"%1`""
if ($PSCmdlet.ShouldProcess($keyPath, 'Register Explorer menu')) {
    New-Item -Path "$keyPath\command" -Force | Out-Null
    Set-ItemProperty -Path $keyPath -Name 'MUIVerb' -Value $MenuText
    Set-ItemProperty -Path $keyPath -Name 'Icon' -Value 'shell32.dll,-16761'
    Set-ItemProperty -Path $keyPath -Name 'Position' -Value 'Top'   # first in the classic menu
    Set-ItemProperty -Path "$keyPath\command" -Name '(default)' -Value $command
}

if ($PSCmdlet.ShouldProcess($sendTo, 'Create Send to shortcut')) {
    $shell = New-Object -ComObject WScript.Shell
    $lnk = $shell.CreateShortcut($sendTo)
    $lnk.TargetPath = 'powershell.exe'
    $lnk.Arguments = "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$handler`""
    $lnk.IconLocation = 'shell32.dll,-16761'
    $lnk.Save()
}

Write-Host "Installed. Right-click a file under $RepositoryRoot > '$MenuText'" -ForegroundColor Green
Write-Host '(Windows 11: "Show more options", or "Send to" > "DMS - Approval".)'
